- name: "Update and upgrade apt packages"
  become: true
  apt:
    upgrade: 'yes'
    update_cache: yes

- name: "Installing dependencies"
  apt:
    pkg: [ ansible, git, nano, htop, iotop, expect, telnet, sudo, sshpass, man]
    state: latest

-  name: "Installing SSH"
   apt: pkg=ssh state=latest

- name: "Enable the root user to log on via SSH using a password"
  replace:
    dest: /etc/hostname
    regexp: '#PermitRootLogin prohibit-password'
    replace: 'PermitRootLogin yes' 
    
- name: Restart SSH
  systemd:
    state: restarted
    daemon_reload: yes
    name: ssh
    enabled: yes    

- name: "Install requirements for managing Windows"
  apt:
    pkg: [ python-pip, git, libffi-dev, libssl-dev ]
    state: latest

- name: "Install pywinrm using pip"
  pip:
    name: pywinrm



- debug:
    msg: "Setup complete, please reboot this system before running any further playbooks."
